
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int INTTYPE = 12;
  public static final int IDENT = 26;
  public static final int ELSE = 14;
  public static final int PLUS = 2;
  public static final int RPAREN = 6;
  public static final int DOUBLE_EQUALS = 19;
  public static final int GREATER_THAN = 17;
  public static final int SEMI = 11;
  public static final int RCURLY = 8;
  public static final int RETURN = 9;
  public static final int INTCONST = 25;
  public static final int IF = 13;
  public static final int LPAREN = 5;
  public static final int LCURLY = 7;
  public static final int EQUALS = 24;
  public static final int BOOL_AND = 22;
  public static final int BOOL_OR = 23;
  public static final int EOF = 0;
  public static final int LESS_THAN = 15;
  public static final int BOOL_NOT = 21;
  public static final int MINUS = 3;
  public static final int NOT_EQUALS = 20;
  public static final int PRINT = 10;
  public static final int error = 1;
  public static final int GREATER_THAN_OR_EQUAL_TO = 18;
  public static final int LESS_THAN_OR_EQUAL_TO = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "RETURN",
  "PRINT",
  "SEMI",
  "INTTYPE",
  "IF",
  "ELSE",
  "LESS_THAN",
  "LESS_THAN_OR_EQUAL_TO",
  "GREATER_THAN",
  "GREATER_THAN_OR_EQUAL_TO",
  "DOUBLE_EQUALS",
  "NOT_EQUALS",
  "BOOL_NOT",
  "BOOL_AND",
  "BOOL_OR",
  "EQUALS",
  "INTCONST",
  "IDENT"
  };
}

